#spring.datasource.url=jdbc:h2:tcp://localhost/~/sym;
#spring.datasource.driver-class-name=org.h2.Driver
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type=trace

debug: false # ???? ??? ?? ???? ??
management.endpoints.web.exposure.include: "*" # actuator endpoint ?? ?? ????

logging: # ????? ???? ?? ?????? ????
  level:
    com.sym: debug # ??????? ??? ?? ???? debug ??? ???
    org.springframework.web.servlet: debug # ?? ??? debug: false?? ?? ??? debug ??? ???
    org.hibernate.type.descriptor.sql.BasicBinder: trace # JPA ??? ? ?? ??? ? ??? ?? ???? ??????

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/symproject
    username: tlqkrus012345
    password: kyu12345
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 8 ??? ????
  jpa:
    defer-datasource-initialization: true # ????? 2.4 ?? ??? ?? ?????? ?? ??(??? ??? ? ?? ?), ??? ???? ??? ??
    hibernate.ddl-auto: create # ENTITY? ???? ???? ddl?? ?????
    show-sql: true
    properties: # ?? ???? ?? properties ??
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100 # JPA?? ??? ????? ?? ? ?? ???? ???? ??? IN?? ??? ??? ????
  h2.console.enabled: false # h2 ? ?? ????
#  sql.init.mode: always # resources/data.sql ??? ?? ???? ????.

---
# ?? ?? ?? ????? ?? profile ??? --- ???? ?? ????.
spring:
  config.activate.on-profile: testdb # ? ??? ?? profile ??? ????.
                                    # ?? ??? testdb ??, testdb profile? activate ??? ? ? ??? ???.
#  datasource:
#    url: jdbc:h2:mem:symproject;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none
